language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

#env:
  #matrix:
    #- LOWEST_DEPS=""
    #- LOWEST_DEPS="--prefer-lowest"

services:
  - memcached
#  - mysql
#  - postgres

addons:
  mariadb: '10.0'

sudo: required
dist: trusty
# this fixes hhvm builds according to https://docs.travis-ci.com/user/languages/php#HHVM-versions-on-Trusty
group: edge

before_script:
  - pecl install apcu
  - pecl install memcache
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -m
  # - mysql -e 'create database egroupware'
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  #- composer update --prefer-source $LOWEST_DEPS
  - sudo apt-get update -qq
  - sudo apt-get install -y myrepos
  - mr --trust-all --stats up
  # installing phpunit in version suitable for used PHP version
  - composer update phpunit/phpunit
  # install egroupware
  - sudo mkdir /var/lib/egroupware
  - sudo chown travis /var/lib/egroupware

script:
  - php doc/rpm-build/post_install.php --source_dir `pwd`
  - mysql -e 'show tables' egroupware
  # Ubuntu has problems with #!/usr/bin/env php -dapc.enable=1, it stalls forever
  - php -dapc.enable_cli=1 doc/test-cli.php
  - ./doc/php_syntax_check.sh

cache:
  directories:
    - $HOME/.composer/cache